version: '3.8'

services:
  # ------------------ PostgreSQL ------------------
  postgres:
    image: postgres:17.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: airc
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: telcom-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network
    restart: unless-stopped

  # ------------------ pgAdmin ------------------
  pgadmin:
    image: dpage/pgadmin4:9.0.0
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: quan-airc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - pg-network
    restart: unless-stopped

  # ------------------ MinIO ------------------
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - pg-network
    restart: unless-stopped

# ------------------ Networks ------------------
networks:
  pg-network:
    driver: bridge

# ------------------ Volumes ------------------
volumes:
  postgres_data:
  pgadmin_data:
  minio-data:
